version: '3.8'

services:
   ollama:
      image: ollama/ollama:latest
      volumes:
        - ./ollama:/root/.ollama
      ports:
        - "11434:11434"
volumes:
  index_data:
    driver: local
  backups:
    driver: local
